services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: journaled
      POSTGRES_PASSWORD: journaled
      POSTGRES_DB: journaled
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.12"
    working_dir: /app/journaled
    environment:
      DATABASE_URL: postgresql+psycopg://journaled:journaled@db:5432/journaled
    depends_on:
      - db
    # Run migrations to head, then keep container alive (replace with your server later)
    command: >
      /bin/sh -lc "journaled-dev init-db && echo 'DB migrated. You can exec into the container and run CLI commands.' && tail -f /dev/null"
volumes:
  pgdata: {}
