services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
      POSTGRES_DB: ledger
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.12"
    working_dir: /app/ledger
    environment:
      DATABASE_URL: postgresql+psycopg://ledger:ledger@db:5432/ledger
    depends_on:
      - db
    # Run migrations to head, then keep container alive (replace with your server later)
    command: >
      /bin/sh -lc "
      ledger-dev init-db &&
      echo 'DB migrated. You can exec into the container and run CLI commands.' &&
      tail -f /dev/null"
volumes:
  pgdata: {}
