

"""initial

Revision ID: 20e65af87a9f
Revises: 
Create Date: 2025-09-15 10:02:42.106824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e65af87a9f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE', name='accounttype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_accounts_parent_id'), 'accounts', ['parent_id'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_name'), 'parties', ['name'], unique=False)
    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('check_number', sa.String(length=32), nullable=True),
    sa.Column('payee', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('memo_line', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ISSUED', 'VOID', 'CLEARED', name='checkstatus'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checks_check_number'), 'checks', ['check_number'], unique=False)
    op.create_table('statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('opening_bal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_bal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'period_start', 'period_end', name='uq_statement_period')
    )
    op.create_index(op.f('ix_statements_account_id'), 'statements', ['account_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_party_id'), 'transactions', ['party_id'], unique=False)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=False)
    op.create_table('splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'account_id', name='uq_split_transaction_account')
    )
    op.create_index(op.f('ix_splits_account_id'), 'splits', ['account_id'], unique=False)
    op.create_index(op.f('ix_splits_transaction_id'), 'splits', ['transaction_id'], unique=False)
    op.create_table('transaction_reversals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_tx_id', sa.Integer(), nullable=False),
    sa.Column('reversing_tx_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_tx_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reversing_tx_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_tx_id', name='uq_reversal_original'),
    sa.UniqueConstraint('reversing_tx_id', name='uq_reversal_reversing')
    )
    op.create_table('statement_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('fitid', sa.String(length=64), nullable=True),
    sa.Column('matched_split_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['matched_split_id'], ['splits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('statement_id', 'fitid', name='uq_stmtline_fitid')
    )
    op.create_index(op.f('ix_statement_lines_matched_split_id'), 'statement_lines', ['matched_split_id'], unique=False)
    op.create_index(op.f('ix_statement_lines_statement_id'), 'statement_lines', ['statement_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statement_lines_statement_id'), table_name='statement_lines')
    op.drop_index(op.f('ix_statement_lines_matched_split_id'), table_name='statement_lines')
    op.drop_table('statement_lines')
    op.drop_table('transaction_reversals')
    op.drop_index(op.f('ix_splits_transaction_id'), table_name='splits')
    op.drop_index(op.f('ix_splits_account_id'), table_name='splits')
    op.drop_table('splits')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_party_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_statements_account_id'), table_name='statements')
    op.drop_table('statements')
    op.drop_index(op.f('ix_checks_check_number'), table_name='checks')
    op.drop_table('checks')
    op.drop_index(op.f('ix_parties_name'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_accounts_parent_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###

